"""Insula Neuro Score — review-score completion. Each score verified before implementation (see docs/MEDICAL-CONTENT-AUDIT.md)."""
from library import o, single, yn, st, conf, score, band_rules

REVIEWED = "2026-10-03"

def build():
    L = []
    def s(**k):
        d = score(**k); d["lastReviewed"] = REVIEWED; return d

    # ================================================================ TRISS (1995 MTOS coefficients)
    regions = [("head", "Head or neck"), ("face", "Face"), ("chest", "Chest"), ("abdomen", "Abdomen or pelvic contents"), ("extremity", "Extremities or pelvic girdle"), ("external", "External")]
    args = ", ".join(r for r, _ in regions)
    band = lambda b: b
    L.append(s(id="triss", name="Trauma and Injury Severity Score", abbreviation="TRISS", aliases=["triss", "probability of survival", "ps", "trauma survival"],
        category="tbi", subcategory="Trauma survival model", specialties=["Trauma", "Emergency Medicine", "Neurosurgery"],
        version={"label": "TRISS with 1995 MTOS coefficients (Champion et al.)", "detail": "Probability of survival Ps = 1/(1+e^−b); b = b0 + b1·RTS + b2·ISS + b3·age index. Blunt: −0.4499, 0.8085, −0.0835, −1.7430. Penetrating: −2.5355, 0.9934, −0.0651, −1.1360. Age index 1 if 55 years or older. Patients under 15 use the blunt model. The 1987 coefficients (Boyd et al.) are a different version and are not used."},
        purpose="Estimates probability of survival after injury from physiology (RTS), anatomy (ISS), age and mechanism, mainly for trauma-system quality review.",
        intendedPopulation="Injured patients, using first recorded physiology and full AIS coding (Major Trauma Outcome Study population).",
        resultPresentation={"type": "prognostic-category", "typeLabel": "Probability of survival (model)", "meter": False},
        calculatorNotice={"tone": "warning", "title": "Model estimate for quality review", "message": "TRISS was built to compare outcomes between trauma systems. It is a group-level model and is not designed for decisions about an individual patient. AIS severities come from licensed AIS coding (not reproduced)."},
        components=[{"id": "context", "label": "Mechanism and age", "inputs": ["mech", "age"]},
                    {"id": "physiology", "label": "Physiology (RTS codes)", "inputs": ["gcs", "sbp", "rr"]},
                    {"id": "anatomy", "label": "Highest AIS severity by region (ISS)", "inputs": [r for r, _ in regions]}],
        inputDefinitions=[single("mech", "Mechanism", "Mechanism", [o("blunt", "Blunt", 0), o("pen", "Penetrating", 1)]),
                          single("age", "Age", "Age", [o("child", "Under 15 years", 0, detail="Blunt model used regardless of mechanism."), o("adult", "15–54 years", 0), o("older", "55 years or older", 1)]),
                          {"id": "gcs", "type": "integer", "label": "GCS total", "short": "GCS", "min": 3, "max": 15,
                           "pointBands": [{"max": 3, "points": 0}, {"min": 4, "max": 5, "points": 1}, {"min": 6, "max": 8, "points": 2}, {"min": 9, "max": 12, "points": 3}, {"min": 13, "points": 4}]},
                          {"id": "sbp", "type": "integer", "label": "Systolic blood pressure", "short": "SBP", "unit": "mmHg", "min": 0, "max": 300,
                           "pointBands": [{"max": 0, "points": 0}, {"min": 1, "max": 49, "points": 1}, {"min": 50, "max": 75, "points": 2}, {"min": 76, "max": 89, "points": 3}, {"min": 90, "points": 4}]},
                          {"id": "rr", "type": "integer", "label": "Respiratory rate", "short": "RR", "unit": "/min", "min": 0, "max": 80,
                           "pointBands": [{"max": 0, "points": 0}, {"min": 1, "max": 5, "points": 1}, {"min": 6, "max": 9, "points": 2}, {"min": 10, "max": 29, "points": 4}, {"min": 30, "points": 3}]}] +
                         [{"id": r, "type": "integer", "label": lab, "short": lab.split(" ")[0], "min": 0, "max": 6, "help": "Highest AIS severity in this region; 0 = no injury."} for r, lab in regions],
        scoringRules=[{"id": "rts", "expr": "0.9368 * gcs + 0.7326 * sbp + 0.2908 * rr"},
                      {"id": "l1", "expr": "largest(1, %s)" % args}, {"id": "l2", "expr": "largest(2, %s)" % args}, {"id": "l3", "expr": "largest(3, %s)" % args},
                      {"id": "iss", "expr": "l1 == 6 ? 75 : l1 * l1 + l2 * l2 + l3 * l3"},
                      {"id": "pen_model", "expr": "mech == 1 && age_value != 'child' ? 1 : 0"},
                      {"id": "b", "expr": "pen_model == 1 ? -2.5355 + 0.9934 * rts - 0.0651 * iss - 1.1360 * age : -0.4499 + 0.8085 * rts - 0.0835 * iss - 1.7430 * age"}],
        calculationMethod={"type": "expression", "expression": "100 / (1 + exp(-b))", "range": {"min": 0, "max": 100},
                           "formula": "{pen_model == 1 ? 'Penetrating' : 'Blunt'} model · RTS {fixed(rts, 4)} · ISS {iss} · age index {age}", "formulaEquals": False,
                           "display": "{fixed(total, 1)}%", "share": "TRISS Ps {fixed(total, 1)}% ({pen_model == 1 ? 'penetrating' : 'blunt'} model, RTS {fixed(rts, 4)}, ISS {iss})"},
        interpretationRules=[{"state": "ps"}],
        resultStates=[st("ps", "informational", "Ps {fixed(total, 1)}%", "Model-estimated probability of survival from the 1995 MTOS coefficients.", "0–100%",
                         "A group-level estimate used in trauma quality review; interpret with the full clinical picture.")],
        clinicalContext=[{"text": "Combines physiological (RTS) and anatomical (ISS) severity with age and mechanism.", "importance": "major"},
                         {"text": "Used in trauma registries to identify unexpected survivors and deaths for case review."}],
        clinicalInsights=[{"when": "mech == 1 && age_value == 'child'", "importance": "major", "text": "Under 15 years: the blunt model is applied even for penetrating injury."},
                          {"text": "ISS is usually finalised after full investigation; early estimates may change."}],
        limitations=[{"importance": "major", "text": "Not designed or validated for decisions about an individual patient."}, {"importance": "major", "text": "Coefficients derive from the North American MTOS population; calibration varies between systems and eras."},
                     "Unreliable when intubated (RTS respiratory and verbal components).", "ISS counts one injury per region and depends on AIS coding."],
        confounders=conf(("Intubation or sedation", "Distorts GCS and respiratory rate in the RTS."), ("Incomplete injury coding", "Underestimates ISS."), ("Pre-hospital interventions", "Alter first recorded physiology."), ("AIS version", "Severity codes differ between AIS versions.")),
        whatItDoesNotTellYou=["An individual patient's outcome.", "Which injuries are present.", "Quality of care on its own."],
        commonErrors=["Using the 1987 and 1995 coefficient sets interchangeably.", "Using the penetrating model for children under 15.", "Entering raw values instead of RTS codes into the formula."],
        guideSections={"what": "A logistic model estimating probability of survival from RTS, ISS, age and mechanism.",
            "whenToUse": "Trauma registry and quality review; research comparisons between systems.",
            "howToPerform": "Enter mechanism and age group. Enter the first recorded GCS, systolic BP and respiratory rate. Enter the highest AIS severity for each body region. The app derives RTS and ISS and applies the 1995 coefficients.",
            "clinicalContext": "A system-level benchmark, used with case review rather than for individual decisions."},
        sources=[{"citation": "Boyd CR, Tolson MA, Copes WS. Evaluating trauma care: the TRISS method. J Trauma. 1987;27(4):370-378."},
                 {"citation": "Champion HR, et al. Coefficients update (editorial comment). J Trauma. 1995;38:94-95."},
                 {"citation": "Champion HR, Sacco WJ, Copes WS, Gann DS, Gennarelli TA, Flanagan ME. A revision of the Trauma Score. J Trauma. 1989;29(5):623-629.", "doi": "10.1097/00005373-198905000-00017"}],
        licensing={"status": "Published model, original wording", "note": "The AIS dictionary is licensed by AAAM and is not reproduced; only severity numbers are entered."}))

    # ================================================================ SOFA (original)
    def organ(id_, label, short, opts, help=None): return single(id_, label, short, [o(i, t, i, str(i)) for i, t in enumerate(opts)], help=help)
    L.append(s(id="sofa", name="Sequential Organ Failure Assessment (original SOFA)", abbreviation="SOFA", aliases=["sofa", "organ failure", "sepsis", "organ dysfunction"],
        category="neurocritical", subcategory="Organ dysfunction", specialties=["Critical Care", "Neurocritical Care"],
        version={"label": "Original SOFA (Vincent et al. 1996), as tabulated in Sepsis-3 (Singer et al. 2016)", "detail": "Six organ systems scored 0–4, total 0–24. SOFA-2 (JAMA 2025) is a different version with new variables and thresholds and is not combined here."},
        purpose="Describes the degree of organ dysfunction in critically ill adults, repeatedly over time.", intendedPopulation="Adults in intensive care.",
        resultPresentation={"type": "severity", "typeLabel": "Organ dysfunction", "meter": False},
        calculatorNotice={"tone": "info", "title": "Original SOFA, not SOFA-2", "message": "Select the band for each organ using the worst value in the assessment period. Catecholamine doses are µg/kg/min given for at least 1 hour."},
        inputDefinitions=[organ("resp", "Respiration: PaO₂/FiO₂, mmHg (kPa)", "Respiration", ["≥400 (53.3)", "<400 (53.3)", "<300 (40)", "<200 (26.7) with respiratory support", "<100 (13.3) with respiratory support"], help="Scores 3 and 4 require respiratory support."),
                          organ("coag", "Coagulation: platelets, ×10³/µL", "Coagulation", ["≥150", "<150", "<100", "<50", "<20"]),
                          organ("liver", "Liver: bilirubin, mg/dL (µmol/L)", "Liver", ["<1.2 (<20)", "1.2–1.9 (20–32)", "2.0–5.9 (33–101)", "6.0–11.9 (102–204)", ">12.0 (>204)"]),
                          organ("cv", "Cardiovascular", "Cardiovascular", ["MAP ≥70 mmHg", "MAP <70 mmHg", "Dopamine <5 or dobutamine (any dose)", "Dopamine 5.1–15, or epinephrine ≤0.1, or norepinephrine ≤0.1", "Dopamine >15, or epinephrine >0.1, or norepinephrine >0.1"],
                                help="Doses in µg/kg/min, given for at least 1 hour."),
                          organ("cns", "Central nervous system: GCS", "CNS", ["15", "13–14", "10–12", "6–9", "<6"]),
                          organ("renal", "Renal: creatinine, mg/dL (µmol/L), or urine output", "Renal", ["<1.2 (<110)", "1.2–1.9 (110–170)", "2.0–3.4 (171–299)", "3.5–4.9 (300–440) or urine output <500 mL/day", ">5.0 (>440) or urine output <200 mL/day"])],
        calculationMethod={"type": "sum", "range": {"min": 0, "max": 24}, "display": "{total}", "share": "SOFA {total} (R{resp} C{coag} L{liver} CV{cv} CNS{cns} Re{renal})"},
        interpretationRules=[{"when": "total == 0", "state": "zero"}, {"state": "scored"}],
        resultStates=[st("zero", "favorable", "No organ dysfunction measured", "No organ dysfunction measured by SOFA at this assessment.", "0", "SOFA covers six organ systems only; dysfunction elsewhere is not captured."),
                      st("scored", "informational", "SOFA {total}", "Higher totals indicate more organ dysfunction. Change over time is often more informative than a single value.", "1–24",
                         "Interpret each organ score and the trend with the clinical picture.")],
        clinicalContext=[{"text": "Describes organ dysfunction across six systems, repeatedly during an ICU stay.", "importance": "major"},
                         {"text": "Sepsis-3 uses an acute change in total SOFA of 2 or more points as part of its sepsis criteria."}],
        clinicalInsights=[{"text": "Record the timing and whether values are worst-in-24-hours; a pre-existing baseline (e.g. chronic kidney disease) affects interpretation."},
                          {"when": "cns >= 1", "text": "The CNS component uses GCS, which is affected by sedation; many protocols use the best estimate of the unsedated GCS."}],
        limitations=[{"importance": "major", "text": "Published reproductions differ slightly at some boundaries (e.g. dopamine 5, creatinine 5.0); this implementation follows the Sepsis-3 table."},
                     {"importance": "major", "text": "Values below 200 mmHg without respiratory support are not explicitly assigned in the table; follow local convention."},
                     "Catecholamine categories do not include vasopressin or newer agents.", "Not designed as a mortality prediction tool for an individual patient."],
        confounders=conf(("Sedation", "Lowers GCS independently of brain dysfunction."), ("Chronic organ disease", "Raises the baseline score."), ("Transfusion or dialysis", "Changes platelet and creatinine values."), ("Missing arterial blood gas", "Limits the respiratory component.")),
        whatItDoesNotTellYou=["The cause of organ dysfunction.", "Whether infection is present.", "An individual patient's prognosis."],
        commonErrors=["Mixing original SOFA and SOFA-2 thresholds.", "Using a single time point instead of the worst value in the period.", "Scoring respiration 3–4 without respiratory support."],
        relatedScores=[{"id": "sofa2", "relation": "Updated version (under review)"}, {"id": "gcs", "relation": "CNS component"}],
        guideSections={"what": "A score of dysfunction in six organ systems (respiratory, coagulation, liver, cardiovascular, CNS, renal), each 0–4.",
            "whenToUse": "Serial description of organ dysfunction in the ICU; research and Sepsis-3 criteria.",
            "howToPerform": "For each organ, select the band matching the worst value in the assessment period. The total is the sum of the six organ scores.",
            "clinicalContext": "A descriptive and sequential measure; trends and organ-specific scores are interpreted with the clinical picture."},
        sources=[{"citation": "Vincent JL, Moreno R, Takala J, et al. The SOFA (Sepsis-related Organ Failure Assessment) score to describe organ dysfunction/failure. Intensive Care Med. 1996;22(7):707-710."},
                 {"citation": "Singer M, Deutschman CS, Seymour CW, et al. The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3). JAMA. 2016;315(8):801-810.", "doi": "10.1001/jama.2016.0287"}],
        licensing={"status": "Published score, original wording", "note": "No reproduction restrictions identified."}))

    # ================================================================ Graeb (1982)
    lat = lambda id_, side: single(id_, f"{side} lateral ventricle", f"{side} LV", [o(0, "No blood", 0), o(1, "Trace of blood or mild bleeding", 1), o(2, "Less than half filled with blood", 2),
                                                                                  o(3, "More than half filled with blood", 3), o(4, "Filled with blood and expanded", 4)])
    mid = lambda id_, name: single(id_, name, name.split(" ")[0] + " V", [o(0, "No blood", 0), o(1, "Blood present, ventricle normal size", 1), o(2, "Filled with blood and expanded", 2)])
    L.append(s(id="graeb", name="Graeb Score", abbreviation="Graeb", aliases=["graeb", "ivh score", "intraventricular haemorrhage", "intraventricular hemorrhage"],
        category="ich", subcategory="Intraventricular haemorrhage (CT)", specialties=["Neurosurgery", "Neurocritical Care", "Neuroradiology", "Stroke"],
        version={"label": "Original Graeb score (Graeb et al. 1982)", "detail": "Each lateral ventricle 0–4; third and fourth ventricles 0–2 each; total 0–12. The modified Graeb score (Morgan 2013, 0–32) is a different instrument."},
        purpose="Semi-quantitative CT grading of intraventricular haemorrhage burden.", intendedPopulation="Patients with intraventricular haemorrhage on CT (primary or secondary to ICH or SAH).",
        resultPresentation={"type": "imaging-classification", "typeLabel": "IVH burden (CT)", "meter": False},
        components=[{"id": "laterals", "label": "Lateral ventricles", "inputs": ["right", "left"]}, {"id": "midline", "label": "Third and fourth ventricles", "inputs": ["third", "fourth"]}],
        inputDefinitions=[lat("right", "Right"), lat("left", "Left"), mid("third", "Third ventricle"), mid("fourth", "Fourth ventricle")],
        calculationMethod={"type": "sum", "range": {"min": 0, "max": 12}, "display": "{total}", "share": "Graeb {total}"},
        interpretationRules=[{"when": "total == 0", "state": "none"}, {"state": "scored"}],
        resultStates=[st("none", "favorable", "No intraventricular blood", "No intraventricular blood on this scan at this assessment.", "0", "Small amounts of blood can be missed; scan timing matters."),
                      st("scored", "informational", "Graeb {total}", "Higher scores indicate more intraventricular blood and ventricular expansion.", "1–12", "Interpret with clinical status, hydrocephalus and serial imaging.")],
        clinicalContext=[{"text": "A long-standing semi-quantitative IVH grade, used in studies of IVH and its treatment.", "importance": "major"}],
        clinicalInsights=[{"when": "right == 4 || left == 4 || third == 2 || fourth == 2", "importance": "major", "text": "Ventricular expansion is recorded; correlate with clinical signs of hydrocephalus."},
                          {"text": "The modified Graeb score scores more regions and correlated better with IVH volume in its derivation study."}],
        limitations=[{"importance": "major", "text": "Coarse categories correlate only moderately with measured IVH volume."}, "Visual estimation varies between readers.", "Does not include parenchymal haematoma or subarachnoid blood."],
        confounders=conf(("Scan timing", "Blood redistributes and clears over time."), ("Pre-existing ventriculomegaly", "Can be mistaken for expansion."), ("Drain placement", "Alters ventricular size and blood distribution.")),
        whatItDoesNotTellYou=["Whether hydrocephalus requires treatment.", "Individual prognosis.", "The source of the haemorrhage."],
        commonErrors=["Scoring the lateral ventricles together instead of separately.", "Mixing Graeb and modified Graeb scores."],
        relatedScores=[{"id": "ich", "relation": "ICH severity (IVH presence)"}, {"id": "mgraeb", "relation": "Modified version (under review)"}, {"id": "mfisher", "relation": "SAH CT grade including IVH"}],
        guideSections={"what": "A 0–12 CT grade of intraventricular blood across the lateral, third and fourth ventricles.", "whenToUse": "Describing IVH burden on CT, including serial scans.",
            "howToPerform": "Score each lateral ventricle separately from 0 to 4. Score the third and fourth ventricles from 0 to 2. Add the four scores.",
            "clinicalContext": "A descriptor of IVH burden used alongside clinical assessment and other imaging findings."},
        sources=[{"citation": "Graeb DA, Robertson WD, Lapointe JS, Nugent RA, Harrison PB. Computed tomographic diagnosis of intraventricular hemorrhage. Etiology and prognosis. Radiology. 1982;143(1):91-96."}],
        licensing={"status": "Published classification, original wording", "note": "No reproduction restrictions identified."}))

    # ================================================================ FAST-ED
    L.append(s(id="fasted", name="Field Assessment Stroke Triage for Emergency Destination", abbreviation="FAST-ED", aliases=["fast-ed", "fasted", "lvo", "prehospital", "large vessel occlusion"],
        category="stroke", subcategory="Prehospital large vessel occlusion screen", specialties=["Stroke", "Emergency Medicine", "Prehospital"],
        version={"label": "FAST-ED (Lima et al. 2016)", "detail": "Five NIHSS-derived items, 0–9. Denial/neglect uses the published definitions; some EMS services use local question-based adaptations, which are not combined here."},
        purpose="Prehospital estimation of large vessel occlusion likelihood in suspected stroke.", intendedPopulation="Adults with suspected acute stroke, assessed by trained prehospital clinicians.",
        resultPresentation={"type": "classification", "typeLabel": "Large vessel occlusion screen", "meter": False},
        calculatorNotice={"tone": "info", "title": "Screening scale", "message": "Destination thresholds are set by regional stroke protocols. FAST-ED does not confirm a vessel occlusion."},
        inputDefinitions=[single("face", "Facial palsy", "Face", [o(0, "Normal or minor paralysis", 0), o(1, "Partial or complete paralysis", 1)]),
                          single("arm", "Arm weakness", "Arm", [o(0, "No drift", 0), o(1, "Drift or some effort against gravity", 1), o(2, "No effort against gravity or no movement", 2)]),
                          single("speech", "Speech changes", "Speech", [o(0, "Absent", 0), o(1, "Mild to moderate", 1), o(2, "Severe, global aphasia or mute", 2)]),
                          single("eye", "Eye deviation", "Eyes", [o(0, "Absent", 0), o(1, "Partial", 1), o(2, "Forced", 2)]),
                          single("neglect", "Denial / neglect", "Neglect", [o(0, "Absent", 0), o(1, "Extinction to bilateral simultaneous stimulation in only one sensory modality", 1),
                                                                         o(2, "Does not recognise own hand or orients only to one side of the body", 2)])],
        calculationMethod={"type": "sum", "range": {"min": 0, "max": 9}, "display": "{total}", "share": "FAST-ED {total}"},
        interpretationRules=[{"when": "total == 0", "state": "zero"}, {"state": "scored"}],
        resultStates=[st("zero", "favorable", "No deficit on FAST-ED items", "No deficit on the FAST-ED items at this assessment.", "0", "A score of 0 does not exclude stroke."),
                      st("scored", "informational", "FAST-ED {total}", "Higher scores indicate more cortical and motor signs associated with large vessel occlusion.", "1–9",
                         "Integrate with the full assessment and the regional stroke pathway.")],
        clinicalContext=[{"text": "Derived from NIHSS items with high predictive value for large vessel occlusion.", "importance": "major"}],
        clinicalInsights=[{"when": "neglect >= 1", "text": "Denial or neglect suggests a cortical (often right-hemisphere) syndrome."}, {"text": "Re-assess on arrival; deficits can evolve during transport."}],
        limitations=[{"importance": "major", "text": "Does not distinguish ischaemia from haemorrhage or stroke mimics."}, "Posterior circulation occlusions may score low.", "Local EMS adaptations of the neglect item differ from the published definitions."],
        confounders=conf(("Stroke mimics", "Seizure, hypoglycaemia or migraine can produce scorable deficits."), ("Pre-existing deficits", "Raise the score."), ("Reduced consciousness", "Limits speech and neglect testing.")),
        whatItDoesNotTellYou=["Whether a vessel is occluded.", "Haemorrhage versus ischaemia.", "Eligibility for treatment."],
        commonErrors=["Using a local two-question neglect adaptation while reporting the published FAST-ED.", "Scoring speech items in a patient who is simply drowsy."],
        relatedScores=[{"id": "race", "relation": "Prehospital LVO scale"}, {"id": "lams", "relation": "Prehospital motor scale"}, {"id": "nihss", "relation": "Full stroke scale"}],
        guideSections={"what": "A five-item prehospital scale (facial palsy, arm weakness, speech, eye deviation, denial/neglect), 0–9.",
            "whenToUse": "Prehospital assessment of suspected stroke within a regional protocol.",
            "howToPerform": "Score each item from the examination. Add the five item scores.",
            "clinicalContext": "A screening scale; confirmation requires vascular imaging."},
        sources=[{"citation": "Lima FO, Silva GS, Furie KL, et al. Field Assessment Stroke Triage for Emergency Destination: a simple and accurate prehospital scale to detect large vessel occlusion strokes. Stroke. 2016;47(8):1997-2002."}],
        licensing={"status": "Published scale, original wording", "note": "No reproduction restrictions identified."}))

    # ================================================================ mJOA (Benzel 1991, clinician-rated)
    L.append(s(id="mjoa", name="Modified Japanese Orthopaedic Association Score", abbreviation="mJOA", aliases=["mjoa", "myelopathy", "dcm", "cervical myelopathy", "benzel"],
        category="spine", subcategory="Cervical myelopathy", specialties=["Neurosurgery", "Spine Surgery", "Neurology"],
        version={"label": "mJOA, clinician-rated (Benzel et al. 1991), 0–18", "detail": "Upper-limb motor 0–5, lower-limb motor 0–7, upper-limb sensation 0–3, micturition 0–3. Severity bands from Tetreault/Fehlings (2017). Not the original JOA (1975, 17 points) and not the patient-derived mJOA."},
        purpose="Clinician-rated severity of degenerative cervical myelopathy.", intendedPopulation="Adults with degenerative cervical myelopathy.",
        resultPresentation={"type": "severity", "typeLabel": "Myelopathy severity", "meter": True},
        inputDefinitions=[single("ue", "Upper-limb motor function", "Upper motor", [o(0, "Unable to move hands", 0), o(1, "Unable to eat with a spoon but able to move hands", 1), o(2, "Unable to button shirt but able to eat with a spoon", 2),
                              o(3, "Able to button shirt with great difficulty", 3), o(4, "Able to button shirt with slight difficulty", 4), o(5, "No dysfunction", 5)]),
                          single("le", "Lower-limb motor function", "Lower motor", [o(0, "Complete loss of motor and sensory function", 0), o(1, "Sensory preservation without ability to move legs", 1), o(2, "Able to move legs but unable to walk", 2),
                              o(3, "Able to walk on a flat floor with a walking aid", 3), o(4, "Able to walk up and/or down stairs with a hand rail", 4),
                              o(5, "Moderate to significant lack of stability, but walks up and/or down stairs without a hand rail", 5), o(6, "Mild lack of stability; walks unaided with smooth reciprocation", 6), o(7, "No dysfunction", 7)]),
                          single("sens", "Upper-limb sensation", "Sensation", [o(0, "Complete loss of hand sensation", 0), o(1, "Severe sensory loss or pain", 1), o(2, "Mild sensory loss", 2), o(3, "No sensory loss", 3)]),
                          single("bladder", "Micturition", "Sphincter", [o(0, "Unable to micturate voluntarily", 0), o(1, "Marked difficulty with micturition", 1), o(2, "Mild to moderate difficulty with micturition", 2), o(3, "Normal micturition", 3)])],
        calculationMethod={"type": "sum", "range": {"min": 0, "max": 18}, "display": "{total}", "share": "mJOA {total}"},
        interpretationRules=[{"when": "total == 18", "state": "none"}] + band_rules([(11, "severe"), (14, "moderate"), (None, "mild")]),
        resultStates=[st("severe", "high", "Severe myelopathy", "mJOA 0–11: severe myelopathy.", "0–11", "Correlate with examination, imaging and progression according to local practice.", 0, 11),
                      st("moderate", "moderate", "Moderate myelopathy", "mJOA 12–14: moderate myelopathy.", "12–14", None, 12, 14),
                      st("mild", "mild", "Mild myelopathy", "mJOA 15–17: mild myelopathy.", "15–17", None, 15, 17),
                      st("none", "favorable", "No dysfunction measured", "mJOA 18: no dysfunction measured at this assessment.", "18", "Does not exclude imaging cord compression or subtle signs.", 18, 18)],
        clinicalContext=[{"text": "The standard clinician-rated severity measure for degenerative cervical myelopathy in Western practice.", "importance": "major"}],
        clinicalInsights=[{"text": "Report the domain scores with the total; motor items carry 12 of 18 points."}, {"text": "Compare serial scores using the same version (mJOA and JOA are not interchangeable)."}],
        limitations=[{"importance": "major", "text": "Not interchangeable with the original JOA score (1975) or the patient-derived mJOA."}, "Upper-limb sensation only; lower-limb and trunk sensation are not scored.", "Function can be limited by non-myelopathic conditions."],
        confounders=conf(("Peripheral neuropathy or carpal tunnel syndrome", "Lowers hand sensation and dexterity."), ("Lower-limb arthritis", "Limits walking."), ("Urological disease", "Affects the micturition item.")),
        whatItDoesNotTellYou=["Imaging severity of compression.", "Whether surgery is appropriate.", "Rate of progression on its own."],
        commonErrors=["Mixing JOA (17-point) and mJOA (18-point) totals.", "Scoring lower-limb items from imaging rather than function."],
        relatedScores=[{"id": "nurick", "relation": "Myelopathy grade"}, {"id": "joa", "relation": "Original JOA (under review)"}],
        guideSections={"what": "An 18-point clinician-rated scale of upper- and lower-limb motor function, hand sensation and micturition.",
            "whenToUse": "Severity grading and follow-up of degenerative cervical myelopathy.",
            "howToPerform": "Score each of the four domains from history and examination. Add the four domain scores.",
            "clinicalContext": "Used with examination findings, imaging and the time course."},
        sources=[{"citation": "Benzel EC, Lancon J, Kesterson L, Hadden T. Cervical laminectomy and dentate ligament section for cervical spondylotic myelopathy. J Spinal Disord. 1991;4(3):286-295."},
                 {"citation": "Tetreault L, Kopjar B, Nouri A, et al. The modified Japanese Orthopaedic Association scale: establishing criteria for mild, moderate and severe impairment in patients with degenerative cervical myelopathy. Eur Spine J. 2017;26(1):78-84."}],
        licensing={"status": "Published clinician-rated scale", "note": "Reproduced in open-access literature. The patient-derived mJOA (myelopathy.org, reproduced with permission) is a separate instrument and is not implemented."}))

    # ================================================================ GPA (original 2008)
    L.append(s(id="gpa", name="Graded Prognostic Assessment (original)", abbreviation="GPA", aliases=["gpa", "brain metastases", "sperduto", "rtog"],
        category="oncology", subcategory="Brain metastases prognosis", specialties=["Neuro-oncology", "Radiation Oncology", "Neurosurgery", "Oncology"],
        version={"label": "Original GPA (Sperduto et al. 2008, RTOG database)", "detail": "Four factors scored 0, 0.5 or 1; total 0–4. Superseded for most primaries by disease-specific GPAs (DS-GPA, updated GPAs), which are separate versions and are not combined here."},
        purpose="Estimates median survival group for patients with brain metastases.", intendedPopulation="Adults with brain metastases (derived from 1,960 RTOG trial patients).",
        resultPresentation={"type": "prognostic-category", "typeLabel": "Prognostic group (median survival)", "meter": False},
        calculatorNotice={"tone": "warning", "title": "Original, non-disease-specific GPA", "message": "Disease-specific GPAs are preferred where one exists for the primary tumour. Survival figures are RTOG trial medians from the 2008 derivation."},
        inputDefinitions=[single("age", "Age", "Age", [o("o60", "Over 60 years", 0), o("50to60", "50–60 years", 0.5, detail="Some reproductions print 50–59."), o("u50", "Under 50 years", 1)]),
                          single("kps", "Karnofsky Performance Status", "KPS", [o("lt70", "Below 70", 0), o("70to80", "70–80", 0.5), o("90to100", "90–100", 1)]),
                          single("nmets", "Number of brain metastases", "Brain metastases", [o("gt3", "More than 3", 0), o("2to3", "2–3", 0.5), o("one", "1", 1)]),
                          single("ecm", "Extracranial metastases", "Extracranial", [o("present", "Present", 0), o("none", "None", 1)])],
        calculationMethod={"type": "sum", "range": {"min": 0, "max": 4}, "display": "{fixed(total, 1)}", "share": "GPA {fixed(total, 1)}"},
        interpretationRules=[{"when": "total <= 1", "state": "g1"}, {"when": "total <= 2.5", "state": "g2"}, {"when": "total <= 3", "state": "g3"}, {"state": "g4"}],
        resultStates=[st("g1", "high", "GPA 0–1", "Median survival 2.6 months in the RTOG derivation data.", "0–1", "Group-level median from trial patients; integrate with oncology input and current treatment options."),
                      st("g2", "moderate", "GPA 1.5–2.5", "Median survival 3.8 months in the RTOG derivation data.", "1.5–2.5"),
                      st("g3", "mild", "GPA 3", "Median survival 6.9 months in the RTOG derivation data.", "3"),
                      st("g4", "low", "GPA 3.5–4", "Median survival 11.0 months in the RTOG derivation data.", "3.5–4")],
        clinicalContext=[{"text": "The first GPA, combining four factors into a prognostic index for brain metastases.", "importance": "major"}],
        clinicalInsights=[{"importance": "major", "text": "Survival has improved with modern systemic and targeted therapy; derivation medians may underestimate current survival."}],
        limitations=[{"importance": "major", "text": "Superseded for most primaries by disease-specific GPAs."}, "Derived from patients enrolled in RTOG trials, mainly treated with whole-brain radiotherapy.", "Age boundary at 60 is printed differently in some reproductions."],
        confounders=conf(("Performance status estimate", "KPS varies between raters."), ("Imaging completeness", "Affects counts of brain and extracranial metastases.")),
        whatItDoesNotTellYou=["Survival for a specific primary tumour type (see disease-specific GPA).", "Which treatment is appropriate.", "An individual patient's survival."],
        commonErrors=["Using the original GPA when a disease-specific GPA exists for the primary.", "Mixing points from different GPA versions."],
        relatedScores=[{"id": "dsgpa", "relation": "Disease-specific versions (under review)"}, {"id": "kps", "relation": "Input"}],
        guideSections={"what": "A 0–4 prognostic index for brain metastases from age, KPS, number of brain metastases and extracranial metastases.",
            "whenToUse": "Prognostic description where a disease-specific GPA is not available, or for historical comparison.",
            "howToPerform": "Score each of the four factors 0, 0.5 or 1. Add the four scores.",
            "clinicalContext": "One input to multidisciplinary decisions with tumour-specific information."},
        sources=[{"citation": "Sperduto PW, Berkey B, Gaspar LE, Mehta M, Curran W. A new prognostic index and comparison to three other indices for patients with brain metastases: an analysis of 1,960 patients in the RTOG database. Int J Radiat Oncol Biol Phys. 2008;70(2):510-514."}],
        licensing={"status": "Published index, original wording", "note": "No reproduction restrictions identified."}))
    return L

UNDER_REVIEW_NEW = {
    "sofa2": ("Verification", "SOFA-2 (Ranzani et al., JAMA 2025) has detailed sub-rules (organ-support definitions, vasopressor dose categories, alternatives when no arterial blood gas). Only a simplified adaptation was available for verification; not implemented until the full published table is checked."),
    "dsgpa": ("Version", "Disease-specific GPAs (lung, breast, melanoma, renal, GI and others) are separate instruments that are updated frequently; each needs its own verified version before implementation."),
}
