"""Phase 9 — verification evidence per score.
Status values:
  "Verified"            matched a primary or authoritative source seen during this project
  "Verified (secondary)" matched several independent secondary sources (tables/protocols citing the original); primary full text not seen
  "Editorial"           written guidance (limitations, cautions) supported by sources but not a scoring rule; needs clinician review
  "FLAG"                uncertainty: manual verification required (see flags)
"""
V, VS, ED, F = "Verified", "Verified (secondary)", "Editorial", "FLAG"
EVIDENCE = {
 "gcs": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Glasgow structured approach (glasgowcomascale.org); Teasdale 2014; severity bands confirmed in CENTER-TBI/TRACK-TBI paper (Leiden)."),
 "gcsp": dict(calc=V, interp=F, pop=V, lim=ED, src=V, basis="Brennan, Murray & Teasdale 2018 abstract (University of Glasgow repository): GCS − non-reacting pupils, range 1–15.",
              flags=["The 1–8 'severe range' is not defined in the original publication (secondary sources only). Content now states this; clinician to confirm whether any band should be shown."]),
 "gos": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Jennett & Bond 1975 categories; Wilson et al. 1998 structured interview guidance."),
 "gose": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Wilson et al. 1998 (eight categories). Category recorder only; the copyrighted structured interview is required for reliable assignment."),
 "nihss": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="NINDS NIH Stroke Scale PDF (Feb 2024), fetched directly: items, UN rules, coma rules; Martin-Schild 2011 (NIHSS 0).",
               flags=["UN (untestable) items contribute 0 and are flagged; NINDS does not define how UN enters the total. Convention to be confirmed by a stroke clinician.",
                      "Only two coma auto-scoring rules (items 8, 9) are encoded, as warnings; NINDS instructions for other items in coma not encoded."]),
 "mrs": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="van Swieten 1988 standard wording, consistent across multiple trial protocols."),
 "aspects": dict(calc=VS, interp=V, pop=V, lim=ED, src=VS, basis="Barber 2000 region scheme via multiple independent descriptions (Radiopaedia, trial protocol, patent text)."),
 "pcaspects": dict(calc=VS, interp=V, pop=V, lim=ED, src=VS, basis="Puetz 2008 weights (thalami, cerebellar hemispheres, PCA territories 1; midbrain, pons 2) via multiple descriptions."),
 "abcd2": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Johnston 2007 Lancet abstract (PubMed): points, risk groups, 2-day risks."),
 "race": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Pérez de la Ossa 2014 via official EMS cards citing the authors (items 0–9, aphasia/agnosia rule, ≥5 cut-off, sensitivity 0.85)."),
 "lams": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Llanes 2004 items via AHA material; Nazliel 2008 (≥4) by title and summary.",
              flags=["Exact item wording ('drifts down', 'falls rapidly', 'weak grip', 'no grip') confirmed in secondary material only; check against Llanes 2004."]),
 "ich": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Hemphill 2001 abstract (Stroke 32:891): all points; mortality 0/13/26/72/97/100% from tables citing the paper.",
             flags=["Score 6: the app states no derivation patient scored 6 (abstract reports scores up to 5); some summaries list 6 as 100%. Confirm against the paper.",
                    "Removed unverified cohort size from content (sources give 152 and 161)."]),
 "func": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Rost 2008: component table (PMC) and outcome statements from the paper."),
 "hunthess": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Grades and original modifier confirmed (BMJ Best Practice; independent descriptions). Grade IV wording corrected to include 'vegetative disturbances'."),
 "wfns": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Original 1988 table (GCS + motor deficit) confirmed in BMJ Best Practice; GCS 15 + deficit undefined."),
 "fisher": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Fisher 1980 grade definitions and non-monotonic vasospasm relationship via multiple sources."),
 "mfisher": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Frontera 2006 abstract: grades and crude odds ratios (Phase 1 verification)."),
 "marshall": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Marshall 1991 categories via Radiopaedia and published tables; order of precedence for derived category.",
                  flags=["Category is derived from findings using the standard order of precedence; confirm with a neuroradiologist for mixed-lesion edge cases."]),
 "rotterdam": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Maas 2005 items (+1) and 6-month mortality by score via published tables."),
 "rts": dict(calc=V, interp=VS, pop=V, lim=ED, src=V, basis="Champion 1989 coded values and weights (Wikipedia/LITFL citing the paper; DOI confirmed).",
             flags=["The '<4' threshold is described in secondary sources as proposed for identifying severe injury; confirm wording."]),
 "iss": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Baker 1974 sum-of-squares and AIS 6 = 75 rule; ISS >15 major-trauma convention (trial protocols, LITFL)."),
 "sins": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Fisher 2010 (SOSG) abstract; Fourney 2011; AJR 2014 worked examples (Phase 3)."),
 "frankel": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Frankel 1969 grades A–E via multiple descriptions."),
 "nurick": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Nurick 1972 (Brain) grades 0–5 via multiple descriptions."),
 "kps": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="KPS definitions confirmed in ECOG-ACRIN comparison table and trial protocols."),
 "ecog": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="ECOG-ACRIN official page; Oken 1982 (Am J Clin Oncol 5:649-55); public domain (openEHR)."),
 "rtokuhashi": dict(calc=F, interp=V, pop=V, lim=ED, src=VS, basis="Tokuhashi 2005 parameters via WJO reviews and PMC tables.",
                    flags=["CONFLICT: 'Metastases in the vertebral body' is ≥3/2/1 in one reproduction and ≥3/1–2/0 in two others (WJO 2016, PMC review). Implementation uses ≥3/2/1. A user textbook table (Spine Surgery and Peripheral Nerve Surgery 2025, Table 8.1) also shows ≥3/2/1, but that table mixes the 1990 and 2005 versions, so it is weak evidence. Verify against the original 2005 paper (Spine 30:2186) before clinical use. A notice in the calculator states this."]),
 "tomita": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Tomita 2001 factors and points (1/2/4; 0/2/4; 1/2) via several independent tables.",
                flags=["One review table (Global Spine J 2018) gives 3 points for rapid growth; the original 2–10 range requires 4. Implementation uses 4; noted for review."]),

 "triss": dict(calc=VS, interp=V, pop=V, lim=ED, src=VS, basis="1995 MTOS coefficients and age index (<55/≥55) confirmed in multiple papers and calculators citing Champion 1995; children <15 use the blunt model (SFAR). Expected values hand-calculated independently."),
 "sofa": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Sepsis-3 (JAMA 2016) Table 1, adapted from Vincent 1996; consistent with multiple reproductions and the user's ICU Protocols textbook (ch. 84, Table 84.1), which shows the same boundary-wording variants and an apparent renal µmol/L print error (300–400 for 300–440).",
              flags=["Reproductions differ at some boundaries (dopamine ≤5 vs <5; creatinine >5.0 vs ≥5.0; one table gives platelets <25); implementation follows the Sepsis-3 table.",
                     "PaO2/FiO2 <200 without respiratory support is not explicitly assigned in the table."]),
 "graeb": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Graeb 1982 grading via multiple published tables (lateral 0–4 each; third/fourth 0–2 each; total 0–12). Corroborated by user's textbook (Neurosurgery Notes, p. 287)."),
 "fasted": dict(calc=VS, interp=VS, pop=V, lim=ED, src=VS, basis="Lima 2016 items via AHA CPR & ECC document, San Diego County EMS and hospital stroke-centre cards (denial/neglect 0/1/2 published definitions).",
                flags=["No derivation cut-off is applied (not verified); some EMS services use question-based neglect adaptations."]),
 "mjoa": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Benzel 1991 clinician-rated items confirmed in an open-access PMC table and two reproductions; Tetreault 2017 severity bands; bands corroborated by two textbooks (Spine Surgery and Peripheral Nerve Surgery 2025, ch. 5 p. 97; Cervical Spine Surgery 2026, ch. 19 p. 116)."),
 "gpa": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="Sperduto 2008 factors (RTOG trial protocol appendix, BMC tables) and median survival 2.6/3.8/6.9/11.0 months (validation abstract).",
             flags=["Middle age band printed as 50–59 or 50–60 in different reproductions; implemented as 50–60 (lowest band is >60)."]),
 # ---- v0.10 Neurosurgical Examination & Grades (verified 2026-10-08)
 "mrc": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="MRC grades 0–5 as published in the MRC 'Aids' booklet; wording consistent across clinical references. Optional 4−/4/4+ subdivisions deliberately not offered."),
 "mrcss": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Kleyweg 1991 (12 movements, 0–60); De Jonghe 2002 (<48 ICU-acquired weakness); Stevens 2009 framework. Primary full texts not seen in this session."),
 "dtr": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="NINDS Myotatic Reflex Scale (Hallett 1993) grade wording confirmed in an institutional teaching document citing NINDS and Litvan 1996.",
             flags=["The '+' notation (1+–4+) is display convention; the NINDS paper uses plain numerals. Scales that use 5 for sustained clonus are a different version and are not combined."]),
 "clonus": dict(calc=V, interp=ED, pop=V, lim=ED, src=VS, basis="Descriptive categories (absent / unsustained / sustained). StatPearls 'Clonus' (2023) gives >10 beats as sustained; other sources differ, so no beat threshold is encoded.",
                flags=["Descriptive record, not a validated scale; clinician to confirm the wording of 'unsustained'."]),
 "plantar": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Flexor/extensor/equivocal/no response, as described by van Gijn (Babinski sign). Descriptive record."),
 "mas": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Bohannon & Smith 1987 six grades (0, 1, 1+, 2, 3, 4), wording consistent across reproductions."),
 "mts": dict(calc=V, interp=VS, pop=V, lim=ED, src=VS, basis="StrokEngine (McGill): V1–V3, X0–X5 wording, R1/R2 per Boyd & Graham 1999; R2−R1 dynamic component.",
             flags=["StrokEngine states X definitions are identical in Tardieu and MTS, including X5 'joint immovable'; some reproductions of the MTS list X0–X4 only. Confirm against Boyd & Graham 1999.",
                    "R2−R1 is reported as an absolute difference because angle conventions differ between joints."]),
 "hb": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="House & Brackmann 1985 grades I–VI (gross, rest, motion) confirmed in a Cochrane review appendix table and standard reproductions."),
 "gr": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Gardner & Robertson 1988 class thresholds (PTA/SDS) as widely reproduced.",
            flags=["Discordant PTA/SDS: HNO 2021 review states Gardner-Robertson assigns the better class while Silverstein assigns the poorer, and calls the rule contradictory; other sources assign the poorer class. The app reports both classes and assigns none. Confirm against the 1988 paper."]),
 "spetzler": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Spetzler & Martin 1986 size/eloquence/drainage points, consistent across neurosurgical references."),
 "lawtonyoung": dict(calc=V, interp=VS, pop=V, lim=ED, src=VS, basis="Lawton 2010 points (age <20/20–40/>40 = 1/2/3; unruptured 1; diffuse 1) confirmed (Ars Neurochirurgica table). Combined Supp-SM 2–10.",
                     flags=["No Supp-SM threshold (e.g. ≤6) is shown: not confirmed from an accessible source in this session."]),
 "borden": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Borden 1995 types I–III and subtypes a/b (single/multiple-hole) confirmed (Radiopaedia)."),
 "cognard": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Cognard 1995 types I–V confirmed (Radiopaedia, Ars Neurochirurgica), including ectasia >5 mm and 3× the draining vein."),
 "markwalder": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Grades 0–4 wording confirmed (Ars Neurochirurgica).",
                    flags=["Originating paper: cited as Markwalder et al. J Neurosurg 1981;55:390 and Markwalder 1981 review (54:637); confirm which introduced the scale."]),
 "engel": dict(calc=V, interp=V, pop=V, lim=ED, src=VS, basis="Engel 1993 classes and subclasses IA–IVC confirmed (Ars Neurochirurgica); book chapter not seen."),
 "ilae": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="ILAE 2001 (Wieser et al.) document fetched from ilae.org: classes 1–6, 1a, seizure-day and baseline definitions, annual assessment."),
}
# Verified but held back from the app pending licensing review (content and tests retained).
HELD = {"rass": dict(calc=V, interp=V, pop=V, lim=ED, src=V, basis="All ten levels confirmed in multiple trial protocols citing Sessler 2002.",
                     flags=["Licensing: VCU lists RASS as a licensable technology; confirm terms before reinstating.",
                            "Terminology: 'Drowsy' sustained awakening is '>10 s' in most sources and '≥10 s' in VCU's description."])}
